DROP TABLE IF EXISTS DISH_PRODUCT;
DROP TABLE IF EXISTS DISH;
DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE DISH (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    CUISINE VARCHAR(30),
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    TYPE VARCHAR(30) NOT NULL,
    UNITS VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE DISH_PRODUCT (
    DISH_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    PRIMARY KEY (DISH_ID, PRODUCT_ID),
    CONSTRAINT DISH_FG_KEY FOREIGN KEY(DISH_ID) REFERENCES DISH(ID),
    CONSTRAINT PRODUCT_FG_KEY FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID)
)